// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Robust.Cdn;

#nullable disable

namespace Robust.Cdn.Data.Migrations.Cdn
{
    [DbContext(typeof(CdnDbContext))]
    partial class CdnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Robust.Cdn.CdnFork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Fork", (string)null);
                });

            modelBuilder.Entity("Robust.Cdn.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Compression")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("Content", null, t =>
                        {
                            t.HasCheckConstraint("CK_Content_UncompressedSameSize", "Compression != 0 OR octet_length(Data) = Size");
                        });
                });

            modelBuilder.Entity("Robust.Cdn.ContentManifestEntry", b =>
                {
                    b.Property<int>("VersionId")
                        .HasColumnType("integer");

                    b.Property<int>("ManifestIdx")
                        .HasColumnType("integer");

                    b.Property<int>("ContentId")
                        .HasColumnType("integer");

                    b.HasKey("VersionId", "ManifestIdx");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("ContentManifestEntryContentId");

                    b.ToTable("ContentManifestEntry", (string)null);
                });

            modelBuilder.Entity("Robust.Cdn.ContentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountDistinctBlobs")
                        .HasColumnType("integer");

                    b.Property<int>("ForkId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("ManifestData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ManifestHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("TimeAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ForkId", "Version")
                        .IsUnique();

                    b.ToTable("ContentVersion", (string)null);
                });

            modelBuilder.Entity("Robust.Cdn.RequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlobId")
                        .HasColumnType("integer");

                    b.Property<int>("BytesSent")
                        .HasColumnType("integer");

                    b.Property<int>("Compression")
                        .HasColumnType("integer");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlobId");

                    b.HasIndex("VersionId");

                    b.ToTable("RequestLog", (string)null);
                });

            modelBuilder.Entity("Robust.Cdn.RequestLogBlob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("RequestLogBlob", (string)null);
                });

            modelBuilder.Entity("Robust.Cdn.ContentManifestEntry", b =>
                {
                    b.HasOne("Robust.Cdn.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Robust.Cdn.ContentVersion", "ContentVersion")
                        .WithMany("ManifestEntries")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("ContentVersion");
                });

            modelBuilder.Entity("Robust.Cdn.ContentVersion", b =>
                {
                    b.HasOne("Robust.Cdn.CdnFork", "Fork")
                        .WithMany("ContentVersions")
                        .HasForeignKey("ForkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fork");
                });

            modelBuilder.Entity("Robust.Cdn.RequestLog", b =>
                {
                    b.HasOne("Robust.Cdn.RequestLogBlob", "Blob")
                        .WithMany()
                        .HasForeignKey("BlobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Robust.Cdn.ContentVersion", "ContentVersion")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Blob");

                    b.Navigation("ContentVersion");
                });

            modelBuilder.Entity("Robust.Cdn.CdnFork", b =>
                {
                    b.Navigation("ContentVersions");
                });

            modelBuilder.Entity("Robust.Cdn.ContentVersion", b =>
                {
                    b.Navigation("ManifestEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
