// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Robust.Cdn;

#nullable disable

namespace Robust.Cdn.Data.Migrations.Manifest
{
    [DbContext(typeof(ManifestDbContext))]
    partial class ManifestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Robust.Cdn.ForkVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ClientFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngineVersion")
                        .HasColumnType("text");

                    b.Property<int>("ForkId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("ForkId", "Name")
                        .IsUnique();

                    b.ToTable("ForkVersion", (string)null);
                });

            modelBuilder.Entity("Robust.Cdn.ForkVersionServerBuild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FileSize")
                        .HasColumnType("integer");

                    b.Property<int>("ForkVersionId")
                        .HasColumnType("integer");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("ForkVersionId", "FileName")
                        .IsUnique();

                    b.HasIndex("ForkVersionId", "Platform")
                        .IsUnique();

                    b.ToTable("ForkVersionServerBuild", (string)null);
                });

            modelBuilder.Entity("Robust.Cdn.ManifestFork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ServerManifestCache")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Fork", (string)null);
                });

            modelBuilder.Entity("Robust.Cdn.PublishInProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EngineVersion")
                        .HasColumnType("text");

                    b.Property<int>("ForkId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ForkId", "Version")
                        .IsUnique();

                    b.ToTable("PublishInProgress", (string)null);
                });

            modelBuilder.Entity("Robust.Cdn.ForkVersion", b =>
                {
                    b.HasOne("Robust.Cdn.ManifestFork", "Fork")
                        .WithMany("Versions")
                        .HasForeignKey("ForkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fork");
                });

            modelBuilder.Entity("Robust.Cdn.ForkVersionServerBuild", b =>
                {
                    b.HasOne("Robust.Cdn.ForkVersion", "ForkVersion")
                        .WithMany("ServerBuilds")
                        .HasForeignKey("ForkVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForkVersion");
                });

            modelBuilder.Entity("Robust.Cdn.PublishInProgress", b =>
                {
                    b.HasOne("Robust.Cdn.ManifestFork", "Fork")
                        .WithMany("InProgressPublishes")
                        .HasForeignKey("ForkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fork");
                });

            modelBuilder.Entity("Robust.Cdn.ForkVersion", b =>
                {
                    b.Navigation("ServerBuilds");
                });

            modelBuilder.Entity("Robust.Cdn.ManifestFork", b =>
                {
                    b.Navigation("InProgressPublishes");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
